eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/  #\u6CE8\u518C\u4E2D\u5FC3\u670D\u52A1\u5730\u5740
server:
  port: 2021  #\u5F53\u524D\u670D\u52A1\u7AEF\u53E3
spring:
  application:
    name: user  #\u5F53\u524D\u670D\u52A1\u540D
