spring:
  datasource:
    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.150.156:3306?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Sys963-+
    type: com.alibaba.druid.pool.DruidDataSource

#  configuration:
#    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#    #map-underscore-to-camel-case: true
#    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
#    #call-setters-on-nulls: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

